/** curl recipes — the everyday HTTP jobs. */
export const examples = { target: 'https://example.com/api/items' };

export const recipes = [
  {
    id: 'get', name: 'Plain GET',
    category: 'Everyday',
    summary: 'Fetch a URL and print the body.',
    flags: {}, when: 'The simplest thing curl does.', cost: 'None.',
  },
  {
    id: 'get-headers', name: 'See the response headers',
    category: 'Everyday',
    summary: 'Prints headers as well as the body, which is usually what you actually wanted.',
    flags: { include: true, location: true },
    when: 'Checking status codes, redirects, cookies or caching.',
    cost: 'None.',
  },
  {
    id: 'head-only', name: 'Headers only',
    category: 'Everyday',
    summary: 'Sends HEAD and shows just the response headers.',
    flags: { head: true, location: true },
    when: 'You want to know if something exists, not what it contains.',
    cost: 'One request, no body.',
  },
  {
    id: 'post-json', name: 'POST some JSON',
    category: 'Sending data',
    summary: 'The usual API call: a JSON body with the right content type.',
    flags: { request: 'POST', header: 'Content-Type: application/json',
             data: '{"name":"test","value":1}', include: true },
    when: 'Talking to a JSON API.',
    cost: 'None.',
  },
  {
    id: 'post-form', name: 'POST a form',
    category: 'Sending data',
    summary: 'Sends url-encoded fields the way a browser form would.',
    flags: { data: 'username=admin&password=secret', include: true },
    examples: { target: 'https://example.com/login' },
    when: 'A classic HTML form rather than an API.',
    cost: 'None.',
  },
  {
    id: 'upload-file', name: 'Upload a file',
    category: 'Sending data',
    summary: 'Multipart upload, the same shape a file input produces.',
    flags: { form: 'file=@/path/to/file.txt', include: true },
    examples: { target: 'https://example.com/upload' },
    when: 'Testing an upload endpoint.',
    cost: 'Sends the whole file.',
  },
  {
    id: 'auth-bearer', name: 'With a bearer token',
    category: 'Authentication',
    summary: 'Adds an Authorization header, which is how most APIs expect to be called.',
    flags: { header: 'Authorization: Bearer YOUR_TOKEN_HERE', include: true },
    when: 'Any token-authenticated API.',
    cost: 'Replace the token before running.',
  },
  {
    id: 'auth-basic', name: 'With a username and password',
    category: 'Authentication',
    summary: 'HTTP basic auth, which curl encodes for you.',
    flags: { user: 'admin:password', include: true },
    when: 'An older service, or a router or printer.',
    cost: 'Credentials are sent base64-encoded, not encrypted. Use HTTPS.',
  },
  {
    id: 'cookies', name: 'Keep a session',
    category: 'Authentication',
    summary: 'Saves cookies to a jar and sends them back, so a login persists between calls.',
    flags: { 'cookie-jar': 'cookies.txt', cookie: 'cookies.txt', location: true, include: true },
    when: 'Anything that signs you in and then expects the session.',
    cost: 'Writes cookies.txt beside you.',
  },
  {
    id: 'download', name: 'Download a file',
    category: 'Files',
    summary: 'Saves to disk with the remote filename, following redirects, resuming if interrupted.',
    flags: { location: true, 'remote-name': true, 'continue-at': '-', 'progress-bar': true },
    examples: { target: 'https://example.com/big-file.zip' },
    when: 'Fetching anything you want on disk rather than on screen.',
    cost: 'As large as the file.',
  },
  {
    id: 'debug', name: 'Show me everything',
    category: 'Debugging',
    summary: 'Full request and response, including the TLS handshake.',
    flags: { verbose: true, location: true },
    when: 'Something is failing and the body does not say why.',
    cost: 'Verbose output goes to stderr, so it will not pollute a pipe.',
  },
  {
    id: 'timing', name: 'Where did the time go?',
    category: 'Debugging',
    summary: 'Prints a timing breakdown instead of the body: DNS, connect, TLS, first byte, total.',
    flags: { output: '/dev/null', silent: true,
             'write-out': 'dns=%{time_namelookup}s connect=%{time_connect}s tls=%{time_appconnect}s ttfb=%{time_starttransfer}s total=%{time_total}s\\n' },
    when: 'Something is slow and you need to know which part.',
    cost: 'One request.',
  },
  {
    id: 'ignore-tls', name: 'Ignore a bad certificate',
    category: 'Debugging',
    summary: 'Skips certificate verification. For a lab or a self-signed host only.',
    flags: { insecure: true, include: true, location: true },
    when: 'A test box with a self-signed certificate.',
    cost: 'Never use this against anything real — it removes the protection TLS provides.',
  },
  {
    id: 'via-proxy', name: 'Through a proxy',
    category: 'Debugging',
    summary: 'Routes the request through a local proxy so you can inspect it.',
    flags: { proxy: 'http://127.0.0.1:8080', insecure: true, include: true },
    when: 'You want Burp or ZAP to see the request.',
    cost: '--insecure is usually needed because the proxy re-signs TLS.',
  },
  {
    id: 'retry', name: 'Retry when the network is flaky',
    category: 'Files',
    summary: 'Retries on transient failures with a growing delay, and gives up eventually.',
    flags: { retry: '5', 'retry-delay': '2', 'retry-all-errors': true,
             'max-time': '120', location: true, 'remote-name': true },
    when: 'Scripted downloads, or an unreliable connection.',
    cost: 'Up to five extra attempts.',
  },
];

export const alternatives = {
  include: [{ id: 'head', when: 'you want the headers and NOT the body' },
            { id: 'verbose', when: 'you also want to see what was sent' },
            { id: 'dump-header', when: 'you want the headers in a file instead' }],
  data: [{ id: 'data-raw', when: 'your body starts with @ and must not be read as a file' },
         { id: 'data-binary', when: 'the body must be sent byte for byte' },
         { id: 'data-urlencode', when: 'you want curl to encode the value for you' },
         { id: 'json', when: 'you want curl to set the JSON headers for you' },
         { id: 'form', when: 'the endpoint expects multipart rather than url-encoded' }],
  user: [{ id: 'header', when: 'the API wants a bearer token rather than basic auth' },
         { id: 'netrc', when: 'you would rather keep credentials out of the command line' }],
  output: [{ id: 'remote-name', when: 'you want the remote filename rather than naming it' }],
  'remote-name': [{ id: 'output', when: 'you want to choose the filename yourself' }],
  verbose: [{ id: 'trace', when: 'you need a full hex dump of the traffic' },
            { id: 'trace-ascii', when: 'you want the trace readable' }],
  insecure: [{ id: 'cacert', when: 'you can point curl at the right CA instead — much better' }],
  retry: [{ id: 'retry-max-time', when: 'you want to bound the total time rather than the count' }],
  'max-time': [{ id: 'connect-timeout', when: 'only the connect phase should be bounded' }],
};
