/** docker recipes. Nothing here runs by itself — they are text to copy. */
export const examples = { image: 'nginx:alpine', container: 'my-container' };

export const recipes = [
  {
    id: 'run-interactive', mode: 'run',
    name: 'Shell into a throwaway container',
    category: 'Running things',
    summary: 'Interactive terminal, removed the moment you exit. The one you reach for most.',
    flags: { rm: true, interactive: true, tty: true },
    examples: { command: '/bin/sh' },
    when: 'You want a clean Linux box for two minutes.',
    cost: 'Pulls the image the first time. Nothing is left behind.',
  },
  {
    id: 'run-port', mode: 'run',
    name: 'Run a service in the background',
    category: 'Running things',
    summary: 'Detached, named, with a port published to the host and a restart policy.',
    flags: { detach: true, publish: '8080:80', name: 'web', restart: 'unless-stopped' },
    when: 'Standing something up you want to keep running.',
    cost: 'Runs until stopped. --restart brings it back after a reboot.',
  },
  {
    id: 'run-mount', mode: 'run',
    name: 'Run with your code mounted in',
    category: 'Running things',
    summary: 'Bind-mounts a directory from the host so edits are seen inside.',
    /* A literal path, not "$PWD". The builder quotes values correctly, which
       means a shell variable would be passed through as text rather than
       expanded — so the recipe says what it means instead. */
    flags: { rm: true, interactive: true, tty: true, volume: '/path/to/your/code:/app', workdir: '/app' },
    when: 'Developing against a container rather than installing a toolchain.',
    cost: 'The container writes to your real files. That is the point, and the risk.',
  },
  {
    id: 'run-env', mode: 'run',
    name: 'Run with environment variables',
    category: 'Running things',
    summary: 'Passes configuration in, which is how most images expect to be set up.',
    flags: { rm: true, detach: true, env: 'KEY=value', 'env-file': '.env', name: 'app' },
    when: 'Database passwords, API keys, anything the image reads from the environment.',
    cost: 'Values given with -e are visible in docker inspect. Prefer --env-file.',
  },
  {
    id: 'run-limited', mode: 'run',
    name: 'Run with resource limits',
    category: 'Running things',
    summary: 'Caps memory and CPU so one container cannot take the machine.',
    flags: { rm: true, detach: true, memory: '512m', cpus: '1.5', name: 'app' },
    when: 'Anything untrusted, or anything you have seen misbehave.',
    cost: 'The container is killed if it exceeds the memory limit.',
  },
  {
    id: 'run-locked-down', mode: 'run',
    name: 'Run with the brakes on',
    category: 'Running things',
    summary: 'Read-only filesystem, no new privileges, every capability dropped.',
    flags: { rm: true, 'read-only': true, 'security-opt': 'no-new-privileges',
             'cap-drop': 'ALL', user: '1000:1000' },
    when: 'Running something you do not fully trust.',
    cost: 'Many images need a writable /tmp — add --tmpfs /tmp if it fails.',
  },

  {
    id: 'exec-shell', mode: 'exec',
    name: 'Get a shell in a running container',
    category: 'Looking inside',
    summary: 'Opens an interactive shell in a container that is already up.',
    flags: { interactive: true, tty: true },
    examples: { command: '/bin/sh' },
    when: 'Debugging something that is running now.',
    cost: 'Changes you make vanish when the container is replaced.',
  },
  {
    id: 'exec-root', mode: 'exec',
    name: 'Shell in as root',
    category: 'Looking inside',
    summary: 'Same, but as root — for when the image runs as an unprivileged user.',
    flags: { interactive: true, tty: true, user: 'root' },
    examples: { command: '/bin/sh' },
    when: 'You need to install a tool inside a container to diagnose it.',
    cost: 'Root inside the container. Treat it accordingly.',
  },
  {
    id: 'logs-follow', mode: 'logs',
    name: 'Follow the logs',
    category: 'Looking inside',
    summary: 'Streams output as it happens, with timestamps, starting from the last 100 lines.',
    flags: { follow: true, tail: '100', timestamps: true },
    when: 'Watching a service start, or catching an error as it happens.',
    cost: 'Runs until you stop it.',
  },
  {
    id: 'inspect-json', mode: 'inspect',
    name: 'Everything the daemon knows',
    category: 'Looking inside',
    summary: 'Full JSON for a container, image, network or volume.',
    flags: {},
    when: 'Finding the real mounts, ports, environment or IP address.',
    cost: 'Long output. Add --format to pull out one field.',
  },
  {
    id: 'inspect-ip', mode: 'inspect',
    name: 'Just the IP address',
    category: 'Looking inside',
    summary: 'A Go template that extracts one field instead of printing everything.',
    flags: { format: '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' },
    when: 'You want one value, usually for a script.',
    cost: 'None.',
  },
  {
    id: 'ps-all', mode: 'ps',
    name: 'Every container, running or not',
    category: 'Looking inside',
    summary: 'Includes stopped containers, which is usually what you actually wanted.',
    flags: { all: true },
    when: 'Something exited and you want to know why.',
    cost: 'None.',
  },
  {
    id: 'ps-table', mode: 'ps',
    name: 'A readable container table',
    category: 'Looking inside',
    summary: 'Only the columns worth seeing, instead of the full-width default.',
    flags: { all: true, format: 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}' },
    when: 'The default output wraps and you cannot read it.',
    cost: 'None.',
  },

  {
    id: 'build-tag', mode: 'build',
    name: 'Build an image',
    category: 'Building',
    summary: 'Builds the Dockerfile in the current directory and names the result.',
    flags: { tag: 'myapp:latest' },
    when: 'The ordinary build.',
    cost: 'Uses the cache. Minutes the first time.',
  },
  {
    id: 'build-clean', mode: 'build',
    name: 'Build without the cache',
    category: 'Building',
    summary: 'Ignores cached layers and re-pulls the base image.',
    flags: { tag: 'myapp:latest', 'no-cache': true, pull: true },
    when: 'The build succeeded but produced something stale.',
    cost: 'Slow, by design.',
  },
  {
    id: 'build-args', mode: 'build',
    name: 'Build with build arguments',
    category: 'Building',
    summary: 'Passes values into the Dockerfile and targets one stage of a multi-stage build.',
    flags: { tag: 'myapp:latest', 'build-arg': 'VERSION=1.0', target: 'production' },
    when: 'One Dockerfile that builds several ways.',
    cost: 'Build args are visible in the image history. Never pass secrets this way.',
  },

  {
    id: 'cp-out', mode: 'cp',
    name: 'Copy a file out of a container',
    category: 'Moving things',
    summary: 'Works on stopped containers too, which makes it good for post-mortems.',
    flags: {},
    when: 'Retrieving a log or an artefact.',
    cost: 'None.',
  },
  {
    id: 'save-image', mode: 'save',
    name: 'Save an image to a file',
    category: 'Moving things',
    summary: 'Writes a tar you can carry to a machine with no registry access.',
    flags: { output: 'image.tar' },
    when: 'Air-gapped environments, or sending an image to someone.',
    cost: 'As large as the image.',
  },
  {
    id: 'pull-image', mode: 'pull',
    name: 'Download an image',
    category: 'Moving things',
    summary: 'Fetches an image from a registry without running anything.',
    flags: {},
    when: 'Pre-pulling before you need it, or refreshing a tag.',
    cost: 'Downloads. Size depends on the image.',
  },

  {
    id: 'rm-force', mode: 'rm',
    name: 'Remove a container, running or not',
    category: 'Cleaning up',
    summary: 'Forces removal and takes its anonymous volumes with it.',
    flags: { force: true, volumes: true },
    when: 'Clearing out something stuck.',
    cost: 'Destructive. --volumes deletes anonymous volume data permanently.',
  },
  {
    id: 'stop-timeout', mode: 'stop',
    name: 'Stop, with a grace period',
    category: 'Cleaning up',
    summary: 'Sends SIGTERM, waits, then SIGKILL — thirty seconds instead of the default ten.',
    flags: { timeout: '30' },
    when: 'A service that needs time to finish what it is doing.',
    cost: 'Up to thirty seconds.',
  },
];

export const alternatives = {
  rm: [{ id: 'detach', when: 'you want it to keep running in the background instead' }],
  detach: [{ id: 'rm', when: 'it is a throwaway you want cleaned up on exit' }],
  volume: [{ id: 'mount', when: 'you want the explicit syntax, which is clearer for named volumes' },
           { id: 'tmpfs', when: 'the container only needs scratch space in memory' }],
  env: [{ id: 'env-file', when: 'there is more than one, or any of them is a secret' }],
  memory: [{ id: 'cpus', when: 'CPU is the constraint rather than memory' }],
  publish: [{ id: 'network', when: 'the containers should talk to each other rather than to the host' },
            { id: 'publish-all', when: 'you want every exposed port mapped to a random one' }],
  tag: [{ id: 'output', when: 'you want the build result as a file rather than an image' }],
  'no-cache': [{ id: 'pull', when: 'only the base image is stale' }],
  follow: [{ id: 'tail', when: 'you only want the last few lines, not a live stream' },
           { id: 'since', when: 'you want everything after a point in time' }],
  format: [{ id: 'quiet', when: 'you only need the ids' }],
  force: [{ id: 'volumes', when: 'you also want its anonymous volumes gone' }],
  all: [{ id: 'filter', when: 'you want a specific subset rather than everything' }],
};
