/** tshark recipes. Reading a file is safe; capturing live needs root and
    sends nothing but does read everything on the wire. */
export const examples = { capture: 'capture.pcapng', iface: 'en0' };

export const recipes = [
  {
    id: 'read-summary', name: 'Read a capture',
    category: 'Reading a file',
    summary: 'One line per packet — the view you want first.',
    flags: { r: true },
    when: 'You have a pcap and want to see what is in it.',
    cost: 'Instant. Reads a file, touches no network.',
  },
  {
    id: 'read-detail', name: 'Full detail for every packet',
    category: 'Reading a file',
    summary: 'Every decoded field, the way Wireshark shows it when you expand a packet.',
    flags: { r: true, V: true },
    when: 'You are looking closely at a handful of packets.',
    cost: 'Enormous output on a large file. Pair it with a filter.',
  },
  {
    id: 'read-filter-http', name: 'Only HTTP requests',
    category: 'Reading a file',
    summary: 'A display filter, applied after the file is parsed.',
    flags: { r: true, Y: 'http.request' },
    when: 'Finding the web traffic in a mixed capture.',
    cost: 'Instant.',
  },
  {
    id: 'read-filter-host', name: 'Only one host',
    category: 'Reading a file',
    summary: 'Narrows to traffic to or from a single address.',
    flags: { r: true, Y: 'ip.addr == 10.10.10.10' },
    when: 'You know which machine you care about.',
    cost: 'Instant.',
  },
  {
    id: 'read-creds', name: 'Plaintext credentials',
    category: 'Reading a file',
    summary: 'Pulls out logins carried in the clear by FTP, Telnet, HTTP basic auth and friends.',
    flags: { r: true, 'z': 'credentials', q: true },
    when: 'Showing why plaintext protocols are a problem.',
    cost: 'Instant, and only finds what was never encrypted.',
  },
  {
    id: 'fields-csv', name: 'Pull out specific fields',
    category: 'Extracting data',
    summary: 'Prints chosen fields as a table you can paste into a spreadsheet.',
    flags: { r: true, T: 'fields', e: 'frame.time', E: 'separator=,' },
    when: 'You want data out of a capture, not a reading experience.',
    cost: 'Instant. Repeat -e for each field you want.',
  },
  {
    id: 'conversations', name: 'Who talked to whom',
    category: 'Extracting data',
    summary: 'A conversation table: endpoints, packet counts and bytes each way.',
    flags: { r: true, z: 'conv,ip', q: true },
    when: 'First question of any capture — what are the main flows.',
    cost: 'Instant.',
  },
  {
    id: 'protocol-stats', name: 'What protocols are in here',
    category: 'Extracting data',
    summary: 'A hierarchy of protocols with how much of the capture each accounts for.',
    flags: { r: true, z: 'io,phs', q: true },
    when: 'Getting your bearings in an unfamiliar capture.',
    cost: 'Instant.',
  },
  {
    id: 'export-objects', name: 'Files sent over HTTP',
    category: 'Extracting data',
    summary: 'Writes out every object transferred over HTTP into a folder.',
    flags: { r: true, 'export-objects': 'http,extracted' },
    when: 'Recovering a file that crossed the wire.',
    cost: 'Writes into ./extracted.',
  },
  {
    id: 'capture-live', name: 'Capture live traffic',
    category: 'Capturing',
    summary: 'Captures on an interface and writes to a file. Needs root.',
    flags: { i: true, w: 'capture.pcapng' },
    when: 'You need traffic you do not yet have.',
    cost: 'Needs root, and runs until you stop it. Capture only on a network you are allowed to.',
  },
  {
    id: 'capture-limited', name: 'Capture a fixed amount',
    category: 'Capturing',
    summary: 'Stops on its own after 1,000 packets or 60 seconds, whichever comes first.',
    flags: { i: true, c: '1000', a: 'duration:60', w: 'capture.pcapng' },
    when: 'A sample rather than an open-ended capture.',
    cost: 'Needs root. Bounded, so it will not fill your disk.',
  },
  {
    id: 'capture-filter', name: 'Capture only what you need',
    category: 'Capturing',
    summary: 'A capture filter is applied in the kernel, so unwanted packets are never stored.',
    flags: { i: true, f: 'tcp port 80 or tcp port 443', w: 'web.pcapng' },
    when: 'A busy link where capturing everything is impractical.',
    cost: 'Needs root. -f uses libpcap syntax, which is not the same as -Y.',
  },
  {
    id: 'list-interfaces', name: 'What can I capture on?',
    category: 'Capturing',
    summary: 'Lists the interfaces tshark can see, with their numbers.',
    flags: { D: true },
    when: 'Before any live capture, to get the interface name right.',
    cost: 'Instant.',
  },
];

export const alternatives = {
  Y: [{ id: 'f', when: 'you are capturing live and want to filter in the kernel instead — far cheaper' },
      { id: 'R', when: 'you want a read filter applied during the first pass' }],
  f: [{ id: 'Y', when: 'you are reading a file, where display filters are the right tool' }],
  V: [{ id: 'T', when: 'you want structured output — fields, JSON or PDML — rather than text' },
      { id: 'x', when: 'you want the raw hex and ASCII dump' }],
  T: [{ id: 'V', when: 'you would rather read it than parse it' }],
  c: [{ id: 'a', when: 'you want to stop on time or file size rather than a packet count' }],
  a: [{ id: 'c', when: 'a packet count is the clearer limit' },
      { id: 'b', when: 'you want it to roll into new files rather than stop' }],
  w: [{ id: 'q', when: 'you do not need the file, only the summary on screen' }],
};
